module.exports.fakeData = [
  {
    machineNo: 1,
    lotNo: "123abc",
    model: "cyclinder",
    target: 3000,
    cycleTime: 10,
    prodTotal: 6,
    prodPassed: 6,
    prodFailed: 0,
    downTimeType: 0,
    stateStatus: true,
    oeeIndicator: 1,
    availableIndicator: 1,
    performanceIndicator: 1,
    qualityIndicator: 1,
  },
  {
    machineNo: 1,
    lotNo: "123abc",
    model: "cyclinder",
    target: 3000,
    cycleTime: 10,
    prodTotal: 3,
    prodPassed: 3,
    prodFailed: 0,
    downTimeType: 4,

    stateStatus: false,
    oeeIndicator: 0.25,
    availableIndicator: 0.5,
    performanceIndicator: 0.5,
    qualityIndicator: 1,
  },
  {
    machineNo: 1,
    lotNo: "123abc",
    model: "cyclinder",
    target: 3000,
    cycleTime: 10,
    prodTotal: 0,
    prodPassed: 0,
    prodFailed: 0,
    downTimeType: 4,

    stateStatus: false,
    oeeIndicator: 0,
    availableIndicator: 0,
    performanceIndicator: 0,
    qualityIndicator: 0,
  },
  {
    machineNo: 1,
    lotNo: "123abc",
    model: "cyclinder",
    target: 3000,
    cycleTime: 10,
    prodTotal: 0,
    prodPassed: 0,
    prodFailed: 0,
    downTimeType: 4,

    stateStatus: false,
    oeeIndicator: 0,
    availableIndicator: 0,
    performanceIndicator: 0,
    qualityIndicator: 0,
  },
  {
    machineNo: 1,
    lotNo: "123abc",
    model: "cyclinder",
    target: 3000,
    cycleTime: 10,
    prodTotal: 0,
    prodPassed: 0,
    prodFailed: 0,
    downTimeType: 4,

    stateStatus: false,
    oeeIndicator: 0,
    availableIndicator: 0,
    performanceIndicator: 0,
    qualityIndicator: 0,
  },
  {
    machineNo: 1,
    lotNo: "123abc",
    model: "cyclinder",
    target: 3000,
    cycleTime: 10,
    prodTotal: 0,
    prodPassed: 0,
    prodFailed: 0,
    downTimeType: 4,

    stateStatus: false,
    oeeIndicator: 0,
    availableIndicator: 0,
    performanceIndicator: 0,
    qualityIndicator: 0,
  },
  {
    machineNo: 1,
    lotNo: "123abc",
    model: "cyclinder",
    target: 3000,
    cycleTime: 10,
    prodTotal: 6,
    prodPassed: 6,
    prodFailed: 0,
    downTimeType: 0,

    stateStatus: true,
    oeeIndicator: 1,
    availableIndicator: 1,
    performanceIndicator: 1,
    qualityIndicator: 1,
  },
  {
    machineNo: 1,
    lotNo: "123abc",
    model: "cyclinder",
    target: 3000,
    cycleTime: 10,
    prodTotal: 6,
    prodPassed: 6,
    prodFailed: 0,
    downTimeType: 0,

    stateStatus: true,
    oeeIndicator: 1,
    availableIndicator: 1,
    performanceIndicator: 1,
    qualityIndicator: 1,
  },
  {
    machineNo: 1,
    lotNo: "123abc",
    model: "cyclinder",
    target: 3000,
    cycleTime: 10,
    prodTotal: 6,
    prodPassed: 6,
    prodFailed: 0,
    downTimeType: 0,

    stateStatus: true,
    oeeIndicator: 1,
    availableIndicator: 1,
    performanceIndicator: 1,
    qualityIndicator: 1,
  },
  {
    machineNo: 1,
    lotNo: "123abc",
    model: "cyclinder",
    target: 3000,
    cycleTime: 10,
    prodTotal: 6,
    prodPassed: 6,
    prodFailed: 0,
    downTimeType: 0,

    stateStatus: true,
    oeeIndicator: 1,
    availableIndicator: 1,
    performanceIndicator: 1,
    qualityIndicator: 1,
  },
  {
    machineNo: 2,
    lotNo: "456abc",
    model: "seat",
    target: 2000,
    cycleTime: 6,
    prodTotal: 10,
    prodPassed: 10,
    prodFailed: 0,
    downTimeType: 0,

    stateStatus: true,
    oeeIndicator: 1,
    availableIndicator: 1,
    performanceIndicator: 1,
    qualityIndicator: 1,
  },
  {
    machineNo: 2,
    lotNo: "456abc",
    model: "seat",
    target: 2000,
    cycleTime: 6,
    prodTotal: 10,
    prodPassed: 10,
    prodFailed: 0,
    downTimeType: 0,

    stateStatus: true,
    oeeIndicator: 1,
    availableIndicator: 1,
    performanceIndicator: 1,
    qualityIndicator: 1,
  },
  {
    machineNo: 2,
    lotNo: "456abc",
    model: "seat",
    target: "2000",
    cycleTime: "6",
    prodTotal: "10",
    prodPassed: "10",
    prodFailed: "0",
    downTimeType: 0,

    stateStatus: "true",
    oeeIndicator: "1",
    availableIndicator: "1",
    performanceIndicator: "1",
    qualityIndicator: "1",
  },
  {
    machineNo: 2,
    lotNo: "456abc",
    model: "seat",
    target: 2000,
    cycleTime: 6,
    prodTotal: 10,
    prodPassed: 10,
    prodFailed: 0,
    downTimeType: 0,

    stateStatus: true,
    oeeIndicator: 1,
    availableIndicator: 1,
    performanceIndicator: 1,
    qualityIndicator: 1,
  },
  {
    machineNo: 2,
    lotNo: "456abc",
    model: "seat",
    target: 2000,
    cycleTime: 6,
    prodTotal: 10,
    prodPassed: 10,
    prodFailed: 0,
    downTimeType: 0,

    stateStatus: true,
    oeeIndicator: 1,
    availableIndicator: 1,
    performanceIndicator: 1,
    qualityIndicator: 1,
  },
  {
    machineNo: 2,
    lotNo: "456abc",
    model: "seat",
    target: 2000,
    cycleTime: 6,
    prodTotal: 10,
    prodPassed: 10,
    prodFailed: 0,
    downTimeType: 0,

    stateStatus: true,
    oeeIndicator: 1,
    availableIndicator: 1,
    performanceIndicator: 1,
    qualityIndicator: 1,
  },
  {
    machineNo: 2,
    lotNo: "456abc",
    model: "seat",
    target: 2000,
    cycleTime: 6,
    prodTotal: 10,
    prodPassed: 10,
    prodFailed: 0,
    downTimeType: 0,

    stateStatus: true,
    oeeIndicator: 1,
    availableIndicator: 1,
    performanceIndicator: 1,
    qualityIndicator: 1,
  },
  {
    machineNo: 2,
    lotNo: "456abc",
    model: "seat",
    target: 2000,
    cycleTime: 6,
    prodTotal: 10,
    prodPassed: 10,
    prodFailed: 0,
    downTimeType: 0,

    stateStatus: true,
    oeeIndicator: 1,
    availableIndicator: 1,
    performanceIndicator: 1,
    qualityIndicator: 1,
  },
  {
    machineNo: 2,
    lotNo: "456abc",
    model: "seat",
    target: 2000,
    cycleTime: 6,
    prodTotal: 10,
    prodPassed: 10,
    prodFailed: 0,
    downTimeType: 0,

    stateStatus: true,
    oeeIndicator: 1,
    availableIndicator: 1,
    performanceIndicator: 1,
    qualityIndicator: 1,
  },
  {
    machineNo: 2,
    lotNo: "456abc",
    model: "seat",
    target: 2000,
    cycleTime: 6,
    prodTotal: 10,
    prodPassed: 10,
    prodFailed: 0,
    downTimeType: 0,

    stateStatus: true,
    oeeIndicator: 1,
    availableIndicator: 1,
    performanceIndicator: 1,
    qualityIndicator: 1,
  },
  {
    machineNo: 3,
    lotNo: "456abc",
    model: "seat",
    target: 2000,
    cycleTime: 6,
    prodTotal: 10,
    prodPassed: 10,
    prodFailed: 0,
    downTimeType: 0,

    stateStatus: true,
    oeeIndicator: 1,
    availableIndicator: 1,
    performanceIndicator: 1,
    qualityIndicator: 1,
  },
  {
    machineNo: 3,
    lotNo: "456abc",
    model: "seat",
    target: 2000,
    cycleTime: 6,
    prodTotal: 10,
    prodPassed: 10,
    prodFailed: 0,
    downTimeType: 0,

    stateStatus: true,
    oeeIndicator: 1,
    availableIndicator: 1,
    performanceIndicator: 1,
    qualityIndicator: 1,
  },
  {
    machineNo: 3,
    lotNo: "456abc",
    model: "seat",
    target: 2000,
    cycleTime: 6,
    prodTotal: 10,
    prodPassed: 10,
    prodFailed: 0,
    downTimeType: 0,

    stateStatus: true,
    oeeIndicator: 1,
    availableIndicator: 1,
    performanceIndicator: 1,
    qualityIndicator: 1,
  },
  {
    machineNo: 3,
    lotNo: "456abc",
    model: "seat",
    target: 2000,
    cycleTime: 6,
    prodTotal: 0,
    prodPassed: 0,
    prodFailed: 0,
    downTimeType: 21,
    stateStatus: false,
    oeeIndicator: 0,
    availableIndicator: 0,
    performanceIndicator: 0,
    qualityIndicator: 0,
  },
  {
    machineNo: 3,
    lotNo: "456abc",
    model: "seat",
    target: 2000,
    cycleTime: 6,
    prodTotal: 0,
    prodPassed: 0,
    prodFailed: 0,
    downTimeType: 21,
    stateStatus: false,
    oeeIndicator: 0,
    availableIndicator: 0,
    performanceIndicator: 0,
    qualityIndicator: 0,
  },
  {
    machineNo: 3,
    lotNo: "456abc",
    model: "seat",
    target: 2000,
    cycleTime: 6,
    prodTotal: 0,
    prodPassed: 0,
    prodFailed: 0,
    downTimeType: 21,

    stateStatus: false,
    oeeIndicator: 0,
    availableIndicator: 0,
    performanceIndicator: 0,
    qualityIndicator: 0,
  },
  {
    machineNo: 3,
    lotNo: "456abc",
    model: "seat",
    target: 2000,
    cycleTime: 6,
    prodTotal: 0,
    prodPassed: 0,
    prodFailed: 0,
    downTimeType: 21,

    stateStatus: false,
    oeeIndicator: 0,
    availableIndicator: 0,
    performanceIndicator: 0,
    qualityIndicator: 0,
  },
  {
    machineNo: 3,
    lotNo: "456abc",
    model: "seat",
    target: 2000,
    cycleTime: 6,
    prodTotal: 0,
    prodPassed: 0,
    prodFailed: 0,
    downTimeType: 21,
    stateStatus: false,
    oeeIndicator: 0,
    availableIndicator: 0,
    performanceIndicator: 0,
    qualityIndicator: 0,
  },
  {
    machineNo: 3,
    lotNo: "456abc",
    model: "seat",
    target: 2000,
    cycleTime: 6,
    prodTotal: 0,
    prodPassed: 0,
    prodFailed: 0,
    downTimeType: 21,
    stateStatus: false,
    oeeIndicator: 0,
    availableIndicator: 0,
    performanceIndicator: 0,
    qualityIndicator: 0,
  },
  {
    machineNo: 3,
    lotNo: "456abc",
    model: "seat",
    target: 2000,
    cycleTime: 6,
    prodTotal: 0,
    prodPassed: 0,
    prodFailed: 0,
    downTimeType: 21,
    stateStatus: false,
    oeeIndicator: 0,
    availableIndicator: 0,
    performanceIndicator: 0,
    qualityIndicator: 0,
  },
  {
    machineNo: 4,
    lotNo: "456abc",
    model: "seat",
    target: 2000,
    cycleTime: 6,
    prodTotal: 0,
    prodPassed: 0,
    prodFailed: 0,
    downTimeType: 10,

    stateStatus: false,
    oeeIndicator: 0,
    availableIndicator: 0,
    performanceIndicator: 0,
    qualityIndicator: 0,
  },
  {
    machineNo: 4,
    lotNo: "456abc",
    model: "seat",
    target: 2000,
    cycleTime: 6,
    prodTotal: 0,
    prodPassed: 0,
    prodFailed: 0,
    downTimeType: 10,

    stateStatus: false,
    oeeIndicator: 0,
    availableIndicator: 0,
    performanceIndicator: 0,
    qualityIndicator: 0,
  },
  {
    machineNo: 4,
    lotNo: "456abc",
    model: "seat",
    target: 2000,
    cycleTime: 6,
    prodTotal: 0,
    prodPassed: 0,
    prodFailed: 0,
    downTimeType: 10,

    stateStatus: false,
    oeeIndicator: 0,
    availableIndicator: 0,
    performanceIndicator: 0,
    qualityIndicator: 0,
  },
  {
    machineNo: 4,
    lotNo: "456abc",
    model: "seat",
    target: 2000,
    cycleTime: 6,
    prodTotal: 0,
    prodPassed: 0,
    prodFailed: 0,
    downTimeType: 10,

    stateStatus: false,
    oeeIndicator: 0,
    availableIndicator: 0,
    performanceIndicator: 0,
    qualityIndicator: 0,
  },
  {
    machineNo: 4,
    lotNo: "456abc",
    model: "seat",
    target: 2000,
    cycleTime: 6,
    prodTotal: 0,
    prodPassed: 0,
    prodFailed: 0,
    downTimeType: 10,

    stateStatus: false,
    oeeIndicator: 0,
    availableIndicator: 0,
    performanceIndicator: 0,
    qualityIndicator: 0,
  },
  {
    machineNo: 4,
    lotNo: "456abc",
    model: "seat",
    target: 2000,
    cycleTime: 6,
    prodTotal: 0,
    prodPassed: 0,
    prodFailed: 0,
    downTimeType: 10,

    stateStatus: false,
    oeeIndicator: 0,
    availableIndicator: 0,
    performanceIndicator: 0,
    qualityIndicator: 0,
  },
  {
    machineNo: 4,
    lotNo: "456abc",
    model: "seat",
    target: 2000,
    cycleTime: 6,
    prodTotal: 0,
    prodPassed: 0,
    prodFailed: 0,
    downTimeType: 10,

    stateStatus: false,
    oeeIndicator: 0,
    availableIndicator: 0,
    performanceIndicator: 0,
    qualityIndicator: 0,
  },
  {
    machineNo: 4,
    lotNo: "456abc",
    model: "seat",
    target: 2000,
    cycleTime: 6,
    prodTotal: 0,
    prodPassed: 0,
    prodFailed: 0,
    downTimeType: 10,

    stateStatus: false,
    oeeIndicator: 0,
    availableIndicator: 0,
    performanceIndicator: 0,
    qualityIndicator: 0,
  },
  {
    machineNo: 4,
    lotNo: "456abc",
    model: "seat",
    target: 2000,
    cycleTime: 6,
    prodTotal: 0,
    prodPassed: 0,
    prodFailed: 0,
    downTimeType: 10,

    stateStatus: false,
    oeeIndicator: 0,
    availableIndicator: 0,
    performanceIndicator: 0,
    qualityIndicator: 0,
  },
  {
    machineNo: 4,
    lotNo: "456abc",
    model: "seat",
    target: 2000,
    cycleTime: 6,
    prodTotal: 0,
    prodPassed: 0,
    prodFailed: 0,
    downTimeType: 10,

    stateStatus: false,
    oeeIndicator: 0,
    availableIndicator: 0,
    performanceIndicator: 0,
    qualityIndicator: 0,
  },
];

// module.exports.fakeData = [
//   {
//     machineNo: 1,
//     lotNo: "123abc",
//     model: "cyclinder",
//     target: 3000,
//     cycleTime: 10,
//     prodTotal: 6,
//     prodPassed: 6,
//     prodFailed: 0,
//     downTimeType: 0,
//     stateStatus: true,
//     oeeIndicator: 1,
//     availableIndicator: 1,
//     performanceIndicator: 1,
//     qualityIndicator: 1,
//   },
//   {
//     machineNo: 1,
//     lotNo: "123abc",
//     model: "cyclinder",
//     target: 3000,
//     cycleTime: 10,
//     prodTotal: 3,
//     prodPassed: 3,
//     prodFailed: 0,
//     downTimeType: 4,
//     stateStatus: false,
//     oeeIndicator: 0.25,
//     availableIndicator: 0.5,
//     performanceIndicator: 0.5,
//     qualityIndicator: 1,
//   },
// ];
